### ISSUE TITLE
Is this project/organization still active?

### ISSUE THREAD

**Issue by webmaven** [octobook/octobook#1]

**Comment by geraldb** [comment]
@webmaven  Yes, it's alive and kicking. Please send questions about octobook and friends to the [wwwmake forum](https://groups.google.com/group/wwwmake). Cheers.

**Comment by webmaven** [comment]
There only seem to be two mentions of 'octobook' in that forum (both by you) from just over a year ago...

That doesn't seem particularly active. What am I missing?

**Comment by geraldb** [comment]
@webmaven It's built on Jekyll and many many other libraries. The latest is [texti/texti](https://github.com/texti/texti). Latest check-in by yours truly three minutes ago. Why do you care? Please post questions to the forum / mailing list (if you do).
